In [1]:
import nltk
import pandas as pd
import numpy as np
import re
import unicodedata
from collections import Counter

# Download required NLTK resources
nltk.download('indian')
nltk.download('punkt')
nltk.download('punkt_tab')

print("Libraries imported successfully!")

[nltk_data] Downloading package indian to /root/nltk_data...
[nltk_data]   Unzipping corpora/indian.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

Libraries imported successfully!

In [2]:
from nltk.corpus import indian


print("Available files in Indian corpus:")
print(indian.fileids())

Available files in Indian corpus:
['bangla.pos', 'hindi.pos', 'marathi.pos', 'telugu.pos']

In [3]:

hindi_data = indian.sents('hindi.pos')

print("Number of sentences in Hindi corpus:", len(hindi_data))


for i, sentence in enumerate(hindi_data[:5], 1):
    print(i, sentence)

Number of sentences in Hindi corpus: 540
1 ['पूर्ण', 'प्रतिबंध', 'हटाओ', ':', 'इराक']
2 ['संयुक्त', 'राष्ट्र', '।']
3 ['इराक', 'के', 'विदेश', 'मंत्री', 'ने', 'अमरीका', 'के', 'उस', 'प्रस्ताव', 'का', 'मजाक', 'उड़ाया', 'है', ',', 'जिसमें', 'अमरीका', 'ने', 'संयुक्त', 'राष्ट्र', 'के', 'प्रतिबंधों', 'को', 'इराकी', 'नागरिकों', 'के', 'लिए', 'कम', 'हानिकारक', 'बनाने', 'के', 'लिए', 'कहा', 'है', '।']
4 ['विदेश', 'मंत्री', 'का', 'कहना', 'है', 'कि', 'चूंकि', 'बगदाद', 'संयुक्त', 'राष्ट्र', 'की', 'मांगों', 'का', 'पालन', 'करते', 'हुए', 'अपने', 'भारी', 'विनाशकारी', 'हथियारों', 'को', 'नष्ट', 'कर', 'रहा', 'है', '।']
5 ['लिहाजा', 'प्रतिबंधों', 'को', 'पूर्ण', 'रूप', 'से', 'उठा', 'दिया', 'जाना', 'चाहिए', '।']

In [4]:

sentences = hindi_data[:500]

print("Number of sentences selected:", len(sentences))

Number of sentences selected: 500

In [5]:
def preprocess_token(token):
    """
    Basic preprocessing:
    - Unicode normalization
    - Remove unwanted punctuation
    - Remove extra spaces
    """

    token = unicodedata.normalize("NFC", token)
    token = token.strip()


    if re.fullmatch(r'[^\w\u0900-\u097F]+', token):
        return ""

    return token


processed_tokens = []

for sentence in sentences:
    for token in sentence:
        token = preprocess_token(token)

        if token:
            processed_tokens.append(token)

print("Total processed tokens:", len(processed_tokens))

print("\nFirst 50 processed tokens:")
print(processed_tokens[:50])

Total processed tokens: 8569

First 50 processed tokens:
['पूर्ण', 'प्रतिबंध', 'हटाओ', 'इराक', 'संयुक्त', 'राष्ट्र', '।', 'इराक', 'के', 'विदेश', 'मंत्री', 'ने', 'अमरीका', 'के', 'उस', 'प्रस्ताव', 'का', 'मजाक', 'उड़ाया', 'है', 'जिसमें', 'अमरीका', 'ने', 'संयुक्त', 'राष्ट्र', 'के', 'प्रतिबंधों', 'को', 'इराकी', 'नागरिकों', 'के', 'लिए', 'कम', 'हानिकारक', 'बनाने', 'के', 'लिए', 'कहा', 'है', '।', 'विदेश', 'मंत्री', 'का', 'कहना', 'है', 'कि', 'चूंकि', 'बगदाद', 'संयुक्त', 'राष्ट्र']

In [6]:

total_tokens = len(processed_tokens)


vocabulary = set(processed_tokens)
vocabulary_size = len(vocabulary)

print("Total Tokens:", total_tokens)
print("Vocabulary Size:", vocabulary_size)

Total Tokens: 8569
Vocabulary Size: 2107

In [7]:

token_frequency = Counter(processed_tokens)


most_common_tokens = token_frequency.most_common(10)

print("10 Most Frequent Tokens:")
print()

for token, frequency in most_common_tokens:
    print(f"{token} -> {frequency}")

10 Most Frequent Tokens:

। -> 453
के -> 359
में -> 255
की -> 209
ने -> 196
है -> 189
को -> 150
से -> 131
पर -> 120
का -> 119

In [8]:
q1_stats = pd.DataFrame({
    "Statistic": [
        "Number of sentences",
        "Total tokens",
        "Vocabulary size"
    ],
    "Value": [
        len(sentences),
        total_tokens,
        vocabulary_size
    ]
})

q1_stats

             Statistic  Value
0  Number of sentences    500
1         Total tokens   8569
2      Vocabulary size   2107

In [9]:
print("""
Observations:

1. Indic languages contain many scripts such as Devanagari, Bengali,
   Telugu, Tamil, Kannada, Malayalam, etc.

2. Word boundaries are not always handled in the same way as English.

3. Indian languages contain many Unicode characters including
   vowel signs, combining marks and special characters.

4. The same word may appear with slightly different Unicode
   representations.

5. Punctuation and symbols can be attached to words, which makes
   tokenization difficult.

6. Code-mixed text such as "Aaj college jaana hai" contains both
   Roman and Indic language elements.

7. Spelling variations are common in social media text.

8. Some Indian languages have rich morphology, so one word may have
   many different forms.
""")

Observations:

1. Indic languages contain many scripts such as Devanagari, Bengali,
   Telugu, Tamil, Kannada, Malayalam, etc.

2. Word boundaries are not always handled in the same way as English.

3. Indian languages contain many Unicode characters including
   vowel signs, combining marks and special characters.

4. The same word may appear with slightly different Unicode
   representations.

5. Punctuation and symbols can be attached to words, which makes
   tokenization difficult.

6. Code-mixed text such as "Aaj college jaana hai" contains both
   Roman and Indic language elements.

7. Spelling variations are common in social media text.

8. Some Indian languages have rich morphology, so one word may have
   many different forms.

In [10]:
noisy_texts = [
    "नमस्ते   दुनिया!!!",
    "आज मौसम बहुत अच्छा है.....",
    "मुझे   Python सीखना है!!!",
    "आप कैसे हैं????",
    "यह   बहुत अच्छा   है।",
    "दिल्ली में आज १२३ लोग आए।",
    "मेरा नाम राहुल है!!!!",
    "क्या आप मेरी मदद कर सकते हैं???",
    "यह बहुत बहुत अच्छा है!!!",
    "आज कॉलेज जाना है......",
    "मुझे NLP पसंद है!!!",
    "आपका स्वागत है :) :)",
    "हेलो     कैसे हो????",
    "यह एक   उदाहरण है।",
    "मुझे Machine Learning सीखनी है!!!",
    "आज तापमान ३० डिग्री है।",
    "वाह!!!! यह तो कमाल है!!!!",
    "कल परीक्षा है..... मुझे पढ़ना है!!!",
    "आप कहाँ जा रहे हैं???",
    "मुझे हिंदी   और English दोनों आती हैं।",
    "GOOD MORNING!!! आज का दिन अच्छा है।",
    "यह बहुत IMPORTANT है!!!!",
    "मेरा मोबाइल नंबर १२३४५६७८९० है।",
    "क्या यह सही है?????",
    "नमस्ते!!!!! आप कैसे हैं????"
]

print("Number of noisy samples:", len(noisy_texts))

for i, text in enumerate(noisy_texts[:5], 1):
    print(i, text)

Number of noisy samples: 25
1 नमस्ते   दुनिया!!!
2 आज मौसम बहुत अच्छा है.....
3 मुझे   Python सीखना है!!!
4 आप कैसे हैं????
5 यह   बहुत अच्छा   है।

In [11]:


indic_digit_map = str.maketrans(
    "०१२३४५६७८९",
    "0123456789"
)


def normalize_indic_text(text):
    """
    Normalizes Indic and mixed-language text.
    """


    text = unicodedata.normalize("NFC", text)


    text = text.translate(indic_digit_map)


    text = re.sub(r'\s+', ' ', text)


    text = re.sub(r'\s+([,.!?।])', r'\1', text)


    text = re.sub(r'([!?.,।])\1+', r'\1', text)


    text = re.sub(r'([~*_+=-])\1+', r'\1', text)


    text = re.sub(r'\s*([,.!?।])\s*', r'\1 ', text)


    text = text.lower()


    text = text.strip()

    return text

In [12]:
normalized_texts = []

for text in noisy_texts:
    normalized_texts.append(normalize_indic_text(text))


normalization_df = pd.DataFrame({
    "Original Text": noisy_texts,
    "Normalized Text": normalized_texts
})

pd.set_option("display.max_colwidth", None)

normalization_df

,Original Text,Normalized Text
0,नमस्ते दुनिया!!!,नमस्ते दुनिया!
1,आज मौसम बहुत अच्छा है.....,आज मौसम बहुत अच्छा है.
2,मुझे Python सीखना है!!!,मुझे python सीखना है!
3,आप कैसे हैं????,आप कैसे हैं?
4,यह बहुत अच्छा है।,यह बहुत अच्छा है।
5,दिल्ली में आज १२३ लोग आए।,दिल्ली में आज 123 लोग आए।
6,मेरा नाम राहुल है!!!!,मेरा नाम राहुल है!
7,क्या आप मेरी मदद कर सकते हैं???,क्या आप मेरी मदद कर सकते हैं?
8,यह बहुत बहुत अच्छा है!!!,यह बहुत बहुत अच्छा है!
9,आज कॉलेज जाना है......,आज कॉलेज जाना है.
10,मुझे NLP पसंद है!!!,मुझे nlp पसंद है!
11,आपका स्वागत है :) :),आपका स्वागत है :) :)
12,हेलो कैसे हो????,हेलो कैसे हो?
13,यह एक उदाहरण है।,यह एक उदाहरण है।
14,मुझे Machine Learning सीखनी है!!!,मुझे machine learning सीखनी है!
15,आज तापमान ३० डिग्री है।,आज तापमान 30 डिग्री है।
16,वाह!!!! यह तो कमाल है!!!!,वाह! यह तो कमाल है!
17,कल परीक्षा है..... मुझे पढ़ना है!!!,कल परीक्षा है. मुझे पढ़ना है!
18,आप कहाँ जा रहे हैं???,आप कहाँ जा रहे हैं?
19,मुझे हिंदी और English दोनों आती हैं।,मुझे हिंदी और english दोनों आती हैं।
20,GOOD MORNING!!! आज का दिन अच्छा है।,good morning! आज का दिन अच्छा है।
21,यह बहुत IMPORTANT है!!!!,यह बहुत important है!
22,मेरा मोबाइल नंबर १२३४५६७८९० है।,मेरा मोबाइल नंबर 1234567890 है।
23,क्या यह सही है?????,क्या यह सही है?
24,नमस्ते!!!!! आप कैसे हैं????,नमस्ते! आप कैसे हैं?

In [13]:
for i in range(len(noisy_texts)):
    print("Original  :", noisy_texts[i])
    print("Normalized:", normalized_texts[i])
    print("-" * 70)

Original  : नमस्ते   दुनिया!!!
Normalized: नमस्ते दुनिया!
----------------------------------------------------------------------
Original  : आज मौसम बहुत अच्छा है.....
Normalized: आज मौसम बहुत अच्छा है.
----------------------------------------------------------------------
Original  : मुझे   Python सीखना है!!!
Normalized: मुझे python सीखना है!
----------------------------------------------------------------------
Original  : आप कैसे हैं????
Normalized: आप कैसे हैं?
----------------------------------------------------------------------
Original  : यह   बहुत अच्छा   है।
Normalized: यह बहुत अच्छा है।
----------------------------------------------------------------------
Original  : दिल्ली में आज १२३ लोग आए।
Normalized: दिल्ली में आज 123 लोग आए।
----------------------------------------------------------------------
Original  : मेरा नाम राहुल है!!!!
Normalized: मेरा नाम राहुल है!
----------------------------------------------------------------------
Original  : क्या आप मेरी मदद कर सकते हैं???
Normalized: क्या आप मेरी मदद कर सकते हैं?
----------------------------------------------------------------------
Original  : यह बहुत बहुत अच्छा है!!!
Normalized: यह बहुत बहुत अच्छा है!
----------------------------------------------------------------------
Original  : आज कॉलेज जाना है......
Normalized: आज कॉलेज जाना है.
----------------------------------------------------------------------
Original  : मुझे NLP पसंद है!!!
Normalized: मुझे nlp पसंद है!
----------------------------------------------------------------------
Original  : आपका स्वागत है :) :)
Normalized: आपका स्वागत है :) :)
----------------------------------------------------------------------
Original  : हेलो     कैसे हो????
Normalized: हेलो कैसे हो?
----------------------------------------------------------------------
Original  : यह एक   उदाहरण है।
Normalized: यह एक उदाहरण है।
----------------------------------------------------------------------
Original  : मुझे Machine Learning सीखनी है!!!
Normalized: मुझे machine learning सीखनी है!
----------------------------------------------------------------------
Original  : आज तापमान ३० डिग्री है।
Normalized: आज तापमान 30 डिग्री है।
----------------------------------------------------------------------
Original  : वाह!!!! यह तो कमाल है!!!!
Normalized: वाह! यह तो कमाल है!
----------------------------------------------------------------------
Original  : कल परीक्षा है..... मुझे पढ़ना है!!!
Normalized: कल परीक्षा है. मुझे पढ़ना है!
----------------------------------------------------------------------
Original  : आप कहाँ जा रहे हैं???
Normalized: आप कहाँ जा रहे हैं?
----------------------------------------------------------------------
Original  : मुझे हिंदी   और English दोनों आती हैं।
Normalized: मुझे हिंदी और english दोनों आती हैं।
----------------------------------------------------------------------
Original  : GOOD MORNING!!! आज का दिन अच्छा है।
Normalized: good morning! आज का दिन अच्छा है।
----------------------------------------------------------------------
Original  : यह बहुत IMPORTANT है!!!!
Normalized: यह बहुत important है!
----------------------------------------------------------------------
Original  : मेरा मोबाइल नंबर १२३४५६७८९० है।
Normalized: मेरा मोबाइल नंबर 1234567890 है।
----------------------------------------------------------------------
Original  : क्या यह सही है?????
Normalized: क्या यह सही है?
----------------------------------------------------------------------
Original  : नमस्ते!!!!! आप कैसे हैं????
Normalized: नमस्ते! आप कैसे हैं?
----------------------------------------------------------------------

In [14]:
print("""
Why text normalization is important:

1. It reduces unnecessary variations in the text.

2. Unicode normalization ensures that visually similar characters
   are represented consistently.

3. Removing repeated punctuation reduces noise.

4. Converting different digit representations to a common form
   makes numerical processing easier.

5. Removing extra spaces helps tokenization.

6. Lowercasing English/Roman-script words reduces vocabulary size.

7. Normalized text improves the performance of NLP tasks such as
   classification, sentiment analysis, information retrieval and
   machine translation.

8. Social media text contains many spelling, punctuation and
   formatting variations, so normalization is especially useful.
""")

Why text normalization is important:

1. It reduces unnecessary variations in the text.

2. Unicode normalization ensures that visually similar characters
   are represented consistently.

3. Removing repeated punctuation reduces noise.

4. Converting different digit representations to a common form
   makes numerical processing easier.

5. Removing extra spaces helps tokenization.

6. Lowercasing English/Roman-script words reduces vocabulary size.

7. Normalized text improves the performance of NLP tasks such as
   classification, sentiment analysis, information retrieval and
   machine translation.

8. Social media text contains many spelling, punctuation and
   formatting variations, so normalization is especially useful.

In [16]:
!pip install indic-transliteration

from indic_transliteration import sanscript
from indic_transliteration.sanscript import transliterate

Collecting indic-transliteration
  Downloading indic_transliteration-2.3.82-py3-none-any.whl.metadata (1.8 kB)
Collecting backports.functools_lru_cache (from indic-transliteration)
  Downloading backports.functools_lru_cache-2.0.0-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.13/dist-packages (from indic-transliteration) (2025.11.3)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from indic-transliteration) (0.27.2)
Requirement already satisfied: toml in /usr/local/lib/python3.13/dist-packages (from indic-transliteration) (0.10.2)
Collecting roman (from indic-transliteration)
  Downloading roman-5.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from indic-transliteration) (4.67.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->indic-transliteration) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->indic-transliteration) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->indic-transliteration) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->indic-transliteration) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->indic-transliteration) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->indic-transliteration) (0.1.2)
Downloading indic_transliteration-2.3.82-py3-none-any.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.9/162.9 kB 5.9 MB/s eta 0:00:00
Downloading backports.functools_lru_cache-2.0.0-py2.py3-none-any.whl (6.7 kB)
Downloading roman-5.2-py3-none-any.whl (6.0 kB)
Installing collected packages: roman, backports.functools_lru_cache, indic-transliteration
Successfully installed backports.functools_lru_cache-2.0.0 indic-transliteration-2.3.82 roman-5.2

In [17]:
devanagari_texts = [
    "नमस्ते, आप कैसे हैं?",
    "मेरा नाम राहुल है।",
    "भारत एक महान देश है।",
    "मुझे हिंदी भाषा पसंद है।",
    "आज मौसम बहुत अच्छा है।"
]

bengali_texts = [
    "নমস্কার, আপনি কেমন আছেন?",
    "আমার নাম রাহুল।",
    "ভারত একটি মহান দেশ।",
    "আমি বাংলা ভাষা পছন্দ করি।",
    "আজ আবহাওয়া খুব ভালো।"
]

print("Devanagari examples:")
for text in devanagari_texts:
    print(text)

print("\nBengali examples:")
for text in bengali_texts:
    print(text)

Devanagari examples:
नमस्ते, आप कैसे हैं?
मेरा नाम राहुल है।
भारत एक महान देश है।
मुझे हिंदी भाषा पसंद है।
आज मौसम बहुत अच्छा है।

Bengali examples:
নমস্কার, আপনি কেমন আছেন?
আমার নাম রাহুল।
ভারত একটি মহান দেশ।
আমি বাংলা ভাষা পছন্দ করি।
আজ আবহাওয়া খুব ভালো।

In [18]:
def show_unicode(text):
    print("Text:", text)

    for char in text:
        if not char.isspace():
            print(
                char,
                "->",
                hex(ord(char)),
                unicodedata.name(char, "UNKNOWN")
            )


print("Unicode information for Devanagari:")
show_unicode(devanagari_texts[0])

Unicode information for Devanagari:
Text: नमस्ते, आप कैसे हैं?
न -> 0x928 DEVANAGARI LETTER NA
म -> 0x92e DEVANAGARI LETTER MA
स -> 0x938 DEVANAGARI LETTER SA
् -> 0x94d DEVANAGARI SIGN VIRAMA
त -> 0x924 DEVANAGARI LETTER TA
े -> 0x947 DEVANAGARI VOWEL SIGN E
, -> 0x2c COMMA
आ -> 0x906 DEVANAGARI LETTER AA
प -> 0x92a DEVANAGARI LETTER PA
क -> 0x915 DEVANAGARI LETTER KA
ै -> 0x948 DEVANAGARI VOWEL SIGN AI
स -> 0x938 DEVANAGARI LETTER SA
े -> 0x947 DEVANAGARI VOWEL SIGN E
ह -> 0x939 DEVANAGARI LETTER HA
ै -> 0x948 DEVANAGARI VOWEL SIGN AI
ं -> 0x902 DEVANAGARI SIGN ANUSVARA
? -> 0x3f QUESTION MARK

In [19]:
def identify_script(text):
    """
    Rough script identification using Unicode ranges.
    """

    devanagari = 0
    bengali = 0
    latin = 0

    for char in text:
        code = ord(char)

        if 0x0900 <= code <= 0x097F:
            devanagari += 1

        elif 0x0980 <= code <= 0x09FF:
            bengali += 1

        elif ('A' <= char <= 'Z') or ('a' <= char <= 'z'):
            latin += 1

    counts = {
        "Devanagari": devanagari,
        "Bengali": bengali,
        "Latin": latin
    }

    return max(counts, key=counts.get)


print("Script:", identify_script(devanagari_texts[0]))
print("Script:", identify_script(bengali_texts[0]))

Script: Devanagari
Script: Bengali

In [20]:
def script_normalize(text):
    """
    Unicode normalization for Indic scripts.
    NFC combines characters into a standard representation.
    """

    text = unicodedata.normalize("NFC", text)


    text = re.sub(r'\s+', ' ', text)


    text = re.sub(r'\s+([,.!?।])', r'\1', text)

    return text.strip()


normalized_devanagari = [
    script_normalize(text)
    for text in devanagari_texts
]

normalized_bengali = [
    script_normalize(text)
    for text in bengali_texts
]

In [21]:
transliterated_devanagari = [
    transliterate(
        text,
        sanscript.DEVANAGARI,
        sanscript.ITRANS
    )
    for text in normalized_devanagari
]


transliterated_bengali = [
    transliterate(
        text,
        sanscript.BENGALI,
        sanscript.ITRANS
    )
    for text in normalized_bengali
]

In [22]:
q3_data = []

for i in range(5):
    q3_data.append({
        "Script": "Devanagari",
        "Original": devanagari_texts[i],
        "Normalized": normalized_devanagari[i],
        "Transliterated": transliterated_devanagari[i]
    })


for i in range(5):
    q3_data.append({
        "Script": "Bengali",
        "Original": bengali_texts[i],
        "Normalized": normalized_bengali[i],
        "Transliterated": transliterated_bengali[i]
    })


q3_df = pd.DataFrame(q3_data)

q3_df

,Script,Original,Normalized,Transliterated
0,Devanagari,"नमस्ते, आप कैसे हैं?","नमस्ते, आप कैसे हैं?","namaste, Apa kaise haiM?"
1,Devanagari,मेरा नाम राहुल है।,मेरा नाम राहुल है।,merA nAma rAhula hai|
2,Devanagari,भारत एक महान देश है।,भारत एक महान देश है।,bhArata eka mahAna desha hai|
3,Devanagari,मुझे हिंदी भाषा पसंद है।,मुझे हिंदी भाषा पसंद है।,mujhe hiMdI bhAShA pasaMda hai|
4,Devanagari,आज मौसम बहुत अच्छा है।,आज मौसम बहुत अच्छा है।,Aja mausama bahuta achChA hai|
5,Bengali,"নমস্কার, আপনি কেমন আছেন?","নমস্কার, আপনি কেমন আছেন?","namaskAra, Apani kemana AChena?"
6,Bengali,আমার নাম রাহুল।,আমার নাম রাহুল।,AmAra nAma rAhula|
7,Bengali,ভারত একটি মহান দেশ।,ভারত একটি মহান দেশ।,bhArata ekaTi mahAna desha|
8,Bengali,আমি বাংলা ভাষা পছন্দ করি।,আমি বাংলা ভাষা পছন্দ করি।,Ami vAMlA bhAShA paChanda kari|
9,Bengali,আজ আবহাওয়া খুব ভালো।,আজ আবহাওয়া খুব ভালো।,Aja AvahAoya়A khuva bhAlo|

In [23]:
for row in q3_data:
    print("Script       :", row["Script"])
    print("Original     :", row["Original"])
    print("Normalized   :", row["Normalized"])
    print("Transliterated:", row["Transliterated"])
    print("-" * 80)

Script       : Devanagari
Original     : नमस्ते, आप कैसे हैं?
Normalized   : नमस्ते, आप कैसे हैं?
Transliterated: namaste, Apa kaise haiM?
--------------------------------------------------------------------------------
Script       : Devanagari
Original     : मेरा नाम राहुल है।
Normalized   : मेरा नाम राहुल है।
Transliterated: merA nAma rAhula hai|
--------------------------------------------------------------------------------
Script       : Devanagari
Original     : भारत एक महान देश है।
Normalized   : भारत एक महान देश है।
Transliterated: bhArata eka mahAna desha hai|
--------------------------------------------------------------------------------
Script       : Devanagari
Original     : मुझे हिंदी भाषा पसंद है।
Normalized   : मुझे हिंदी भाषा पसंद है।
Transliterated: mujhe hiMdI bhAShA pasaMda hai|
--------------------------------------------------------------------------------
Script       : Devanagari
Original     : आज मौसम बहुत अच्छा है।
Normalized   : आज मौसम बहुत अच्छा है।
Transliterated: Aja mausama bahuta achChA hai|
--------------------------------------------------------------------------------
Script       : Bengali
Original     : নমস্কার, আপনি কেমন আছেন?
Normalized   : নমস্কার, আপনি কেমন আছেন?
Transliterated: namaskAra, Apani kemana AChena?
--------------------------------------------------------------------------------
Script       : Bengali
Original     : আমার নাম রাহুল।
Normalized   : আমার নাম রাহুল।
Transliterated: AmAra nAma rAhula|
--------------------------------------------------------------------------------
Script       : Bengali
Original     : ভারত একটি মহান দেশ।
Normalized   : ভারত একটি মহান দেশ।
Transliterated: bhArata ekaTi mahAna desha|
--------------------------------------------------------------------------------
Script       : Bengali
Original     : আমি বাংলা ভাষা পছন্দ করি।
Normalized   : আমি বাংলা ভাষা পছন্দ করি।
Transliterated: Ami vAMlA bhAShA paChanda kari|
--------------------------------------------------------------------------------
Script       : Bengali
Original     : আজ আবহাওয়া খুব ভালো।
Normalized   : আজ আবহাওয়া খুব ভালো।
Transliterated: Aja AvahAoya়A khuva bhAlo|
--------------------------------------------------------------------------------

In [24]:
print("""
Observations:

1. Indic languages use multiple scripts such as Devanagari, Bengali,
   Tamil, Telugu, Kannada and Malayalam.

2. Unicode normalization helps represent characters consistently.

3. Transliteration allows text from different scripts to be
   represented using a common representation.

4. Script normalization is useful for multilingual search and
   cross-lingual NLP.

5. It can help reduce problems caused by different representations
   of similar text.

6. Transliteration is particularly useful when users type Indian
   languages using Roman characters.

7. However, transliteration may lose some script-specific information
   and different transliteration schemes may produce different
   outputs.
""")

Observations:

1. Indic languages use multiple scripts such as Devanagari, Bengali,
   Tamil, Telugu, Kannada and Malayalam.

2. Unicode normalization helps represent characters consistently.

3. Transliteration allows text from different scripts to be
   represented using a common representation.

4. Script normalization is useful for multilingual search and
   cross-lingual NLP.

5. It can help reduce problems caused by different representations
   of similar text.

6. Transliteration is particularly useful when users type Indian
   languages using Roman characters.

7. However, transliteration may lose some script-specific information
   and different transliteration schemes may produce different
   outputs.

In [25]:
parallel_data = [
    ("मेरा नाम राहुल है।", "My name is Rahul."),
    ("मैं एक छात्र हूँ।", "I am a student."),
    ("मुझे हिंदी पसंद है।", "I like Hindi."),
    ("आज मौसम बहुत अच्छा है।", "The weather is very nice today."),
    ("मैं कॉलेज जा रहा हूँ।", "I am going to college."),
    ("वह मेरा दोस्त है।", "He is my friend."),
    ("मुझे किताब पढ़ना पसंद है।", "I like reading books."),
    ("भारत एक बड़ा देश है।", "India is a large country."),
    ("मैं रोज़ पढ़ाई करता हूँ।", "I study every day."),
    ("यह मेरा घर है।", "This is my house."),
    ("मुझे संगीत सुनना पसंद है।", "I like listening to music."),
    ("वह बाजार जा रही है।", "She is going to the market."),
    ("आज मेरी परीक्षा है।", "I have my exam today."),
    ("मुझे कंप्यूटर विज्ञान पसंद है।", "I like computer science."),
    ("हम साथ में क्रिकेट खेलते हैं।", "We play cricket together."),
    ("मेरा भाई दिल्ली में रहता है।", "My brother lives in Delhi."),
    ("मैं Python सीख रहा हूँ।", "I am learning Python."),
    ("कृपया दरवाज़ा बंद कर दो।", "Please close the door."),
    ("मुझे पानी चाहिए।", "I need water."),
    ("आपका दिन शुभ हो।", "Have a good day.")
]

print("Number of parallel sentence pairs:", len(parallel_data))

Number of parallel sentence pairs: 20

In [26]:
# Unicode-aware tokenizer
tokenizer = nltk.tokenize.RegexpTokenizer(r'\w+|[^\w\s]', flags=re.UNICODE)


def tokenize_text(text):
    return tokenizer.tokenize(text)


parallel_rows = []

for hindi, english in parallel_data:

    hindi_tokens = tokenize_text(hindi)
    english_tokens = tokenize_text(english)

    parallel_rows.append({
        "Hindi Sentence": hindi,
        "English Sentence": english,
        "Hindi Tokens": hindi_tokens,
        "English Tokens": english_tokens,
        "Hindi Length": len(hindi_tokens),
        "English Length": len(english_tokens)
    })


parallel_df = pd.DataFrame(parallel_rows)

parallel_df

,Hindi Sentence,English Sentence,Hindi Tokens,English Tokens,Hindi Length,English Length
0,मेरा नाम राहुल है।,My name is Rahul.,"[म, े, र, ा, न, ा, म, र, ा, ह, ु, ल, ह, ै, ।]","[My, name, is, Rahul, .]",15,5
1,मैं एक छात्र हूँ।,I am a student.,"[म, ै, ं, एक, छ, ा, त, ्, र, ह, ू, ँ, ।]","[I, am, a, student, .]",13,5
2,मुझे हिंदी पसंद है।,I like Hindi.,"[म, ु, झ, े, ह, ि, ं, द, ी, पस, ं, द, ह, ै, ।]","[I, like, Hindi, .]",15,4
3,आज मौसम बहुत अच्छा है।,The weather is very nice today.,"[आज, म, ौ, सम, बह, ु, त, अच, ्, छ, ा, ह, ै, ।]","[The, weather, is, very, nice, today, .]",14,7
4,मैं कॉलेज जा रहा हूँ।,I am going to college.,"[म, ै, ं, क, ॉ, ल, े, ज, ज, ा, रह, ा, ह, ू, ँ, ।]","[I, am, going, to, college, .]",16,6
5,वह मेरा दोस्त है।,He is my friend.,"[वह, म, े, र, ा, द, ो, स, ्, त, ह, ै, ।]","[He, is, my, friend, .]",13,5
6,मुझे किताब पढ़ना पसंद है।,I like reading books.,"[म, ु, झ, े, क, ि, त, ा, ब, पढ, ़, न, ा, पस, ं, द, ह, ै, ।]","[I, like, reading, books, .]",19,5
7,भारत एक बड़ा देश है।,India is a large country.,"[भ, ा, रत, एक, बड, ़, ा, द, े, श, ह, ै, ।]","[India, is, a, large, country, .]",13,6
8,मैं रोज़ पढ़ाई करता हूँ।,I study every day.,"[म, ै, ं, र, ो, ज, ़, पढ, ़, ा, ई, करत, ा, ह, ू, ँ, ।]","[I, study, every, day, .]",17,5
9,यह मेरा घर है।,This is my house.,"[यह, म, े, र, ा, घर, ह, ै, ।]","[This, is, my, house, .]",9,5
10,मुझे संगीत सुनना पसंद है।,I like listening to music.,"[म, ु, झ, े, स, ं, ग, ी, त, स, ु, नन, ा, पस, ं, द, ह, ै, ।]","[I, like, listening, to, music, .]",19,6
11,वह बाजार जा रही है।,She is going to the market.,"[वह, ब, ा, ज, ा, र, ज, ा, रह, ी, ह, ै, ।]","[She, is, going, to, the, market, .]",13,7
12,आज मेरी परीक्षा है।,I have my exam today.,"[आज, म, े, र, ी, पर, ी, क, ्, ष, ा, ह, ै, ।]","[I, have, my, exam, today, .]",14,6
13,मुझे कंप्यूटर विज्ञान पसंद है।,I like computer science.,"[म, ु, झ, े, क, ं, प, ्, य, ू, टर, व, ि, ज, ्, ञ, ा, न, पस, ं, द, ह, ै, ।]","[I, like, computer, science, .]",24,5
14,हम साथ में क्रिकेट खेलते हैं।,We play cricket together.,"[हम, स, ा, थ, म, े, ं, क, ्, र, ि, क, े, ट, ख, े, लत, े, ह, ै, ं, ।]","[We, play, cricket, together, .]",22,5
15,मेरा भाई दिल्ली में रहता है।,My brother lives in Delhi.,"[म, े, र, ा, भ, ा, ई, द, ि, ल, ्, ल, ी, म, े, ं, रहत, ा, ह, ै, ।]","[My, brother, lives, in, Delhi, .]",21,6
16,मैं Python सीख रहा हूँ।,I am learning Python.,"[म, ै, ं, Python, स, ी, ख, रह, ा, ह, ू, ँ, ।]","[I, am, learning, Python, .]",13,5
17,कृपया दरवाज़ा बंद कर दो।,Please close the door.,"[क, ृ, पय, ा, दरव, ा, ज, ़, ा, ब, ं, द, कर, द, ो, ।]","[Please, close, the, door, .]",16,5
18,मुझे पानी चाहिए।,I need water.,"[म, ु, झ, े, प, ा, न, ी, च, ा, ह, ि, ए, ।]","[I, need, water, .]",14,4
19,आपका दिन शुभ हो।,Have a good day.,"[आपक, ा, द, ि, न, श, ु, भ, ह, ो, ।]","[Have, a, good, day, .]",11,5

In [27]:
for i, row in parallel_df.iterrows():

    print("Pair", i + 1)
    print("Hindi   :", row["Hindi Tokens"])
    print("English :", row["English Tokens"])
    print(
        "Lengths :",
        row["Hindi Length"],
        "vs",
        row["English Length"]
    )
    print("-" * 80)

Pair 1
Hindi   : ['म', 'े', 'र', 'ा', 'न', 'ा', 'म', 'र', 'ा', 'ह', 'ु', 'ल', 'ह', 'ै', '।']
English : ['My', 'name', 'is', 'Rahul', '.']
Lengths : 15 vs 5
--------------------------------------------------------------------------------
Pair 2
Hindi   : ['म', 'ै', 'ं', 'एक', 'छ', 'ा', 'त', '्', 'र', 'ह', 'ू', 'ँ', '।']
English : ['I', 'am', 'a', 'student', '.']
Lengths : 13 vs 5
--------------------------------------------------------------------------------
Pair 3
Hindi   : ['म', 'ु', 'झ', 'े', 'ह', 'ि', 'ं', 'द', 'ी', 'पस', 'ं', 'द', 'ह', 'ै', '।']
English : ['I', 'like', 'Hindi', '.']
Lengths : 15 vs 4
--------------------------------------------------------------------------------
Pair 4
Hindi   : ['आज', 'म', 'ौ', 'सम', 'बह', 'ु', 'त', 'अच', '्', 'छ', 'ा', 'ह', 'ै', '।']
English : ['The', 'weather', 'is', 'very', 'nice', 'today', '.']
Lengths : 14 vs 7
--------------------------------------------------------------------------------
Pair 5
Hindi   : ['म', 'ै', 'ं', 'क', 'ॉ', 'ल', 'े', 'ज', 'ज', 'ा', 'रह', 'ा', 'ह', 'ू', 'ँ', '।']
English : ['I', 'am', 'going', 'to', 'college', '.']
Lengths : 16 vs 6
--------------------------------------------------------------------------------
Pair 6
Hindi   : ['वह', 'म', 'े', 'र', 'ा', 'द', 'ो', 'स', '्', 'त', 'ह', 'ै', '।']
English : ['He', 'is', 'my', 'friend', '.']
Lengths : 13 vs 5
--------------------------------------------------------------------------------
Pair 7
Hindi   : ['म', 'ु', 'झ', 'े', 'क', 'ि', 'त', 'ा', 'ब', 'पढ', '़', 'न', 'ा', 'पस', 'ं', 'द', 'ह', 'ै', '।']
English : ['I', 'like', 'reading', 'books', '.']
Lengths : 19 vs 5
--------------------------------------------------------------------------------
Pair 8
Hindi   : ['भ', 'ा', 'रत', 'एक', 'बड', '़', 'ा', 'द', 'े', 'श', 'ह', 'ै', '।']
English : ['India', 'is', 'a', 'large', 'country', '.']
Lengths : 13 vs 6
--------------------------------------------------------------------------------
Pair 9
Hindi   : ['म', 'ै', 'ं', 'र', 'ो', 'ज', '़', 'पढ', '़', 'ा', 'ई', 'करत', 'ा', 'ह', 'ू', 'ँ', '।']
English : ['I', 'study', 'every', 'day', '.']
Lengths : 17 vs 5
--------------------------------------------------------------------------------
Pair 10
Hindi   : ['यह', 'म', 'े', 'र', 'ा', 'घर', 'ह', 'ै', '।']
English : ['This', 'is', 'my', 'house', '.']
Lengths : 9 vs 5
--------------------------------------------------------------------------------
Pair 11
Hindi   : ['म', 'ु', 'झ', 'े', 'स', 'ं', 'ग', 'ी', 'त', 'स', 'ु', 'नन', 'ा', 'पस', 'ं', 'द', 'ह', 'ै', '।']
English : ['I', 'like', 'listening', 'to', 'music', '.']
Lengths : 19 vs 6
--------------------------------------------------------------------------------
Pair 12
Hindi   : ['वह', 'ब', 'ा', 'ज', 'ा', 'र', 'ज', 'ा', 'रह', 'ी', 'ह', 'ै', '।']
English : ['She', 'is', 'going', 'to', 'the', 'market', '.']
Lengths : 13 vs 7
--------------------------------------------------------------------------------
Pair 13
Hindi   : ['आज', 'म', 'े', 'र', 'ी', 'पर', 'ी', 'क', '्', 'ष', 'ा', 'ह', 'ै', '।']
English : ['I', 'have', 'my', 'exam', 'today', '.']
Lengths : 14 vs 6
--------------------------------------------------------------------------------
Pair 14
Hindi   : ['म', 'ु', 'झ', 'े', 'क', 'ं', 'प', '्', 'य', 'ू', 'टर', 'व', 'ि', 'ज', '्', 'ञ', 'ा', 'न', 'पस', 'ं', 'द', 'ह', 'ै', '।']
English : ['I', 'like', 'computer', 'science', '.']
Lengths : 24 vs 5
--------------------------------------------------------------------------------
Pair 15
Hindi   : ['हम', 'स', 'ा', 'थ', 'म', 'े', 'ं', 'क', '्', 'र', 'ि', 'क', 'े', 'ट', 'ख', 'े', 'लत', 'े', 'ह', 'ै', 'ं', '।']
English : ['We', 'play', 'cricket', 'together', '.']
Lengths : 22 vs 5
--------------------------------------------------------------------------------
Pair 16
Hindi   : ['म', 'े', 'र', 'ा', 'भ', 'ा', 'ई', 'द', 'ि', 'ल', '्', 'ल', 'ी', 'म', 'े', 'ं', 'रहत', 'ा', 'ह', 'ै', '।']
English : ['My', 'brother', 'lives', 'in', 'Delhi', '.']
Lengths : 21 vs 6
--------------------------------------------------------------------------------
Pair 17
Hindi   : ['म', 'ै', 'ं', 'Python', 'स', 'ी', 'ख', 'रह', 'ा', 'ह', 'ू', 'ँ', '।']
English : ['I', 'am', 'learning', 'Python', '.']
Lengths : 13 vs 5
--------------------------------------------------------------------------------
Pair 18
Hindi   : ['क', 'ृ', 'पय', 'ा', 'दरव', 'ा', 'ज', '़', 'ा', 'ब', 'ं', 'द', 'कर', 'द', 'ो', '।']
English : ['Please', 'close', 'the', 'door', '.']
Lengths : 16 vs 5
--------------------------------------------------------------------------------
Pair 19
Hindi   : ['म', 'ु', 'झ', 'े', 'प', 'ा', 'न', 'ी', 'च', 'ा', 'ह', 'ि', 'ए', '।']
English : ['I', 'need', 'water', '.']
Lengths : 14 vs 4
--------------------------------------------------------------------------------
Pair 20
Hindi   : ['आपक', 'ा', 'द', 'ि', 'न', 'श', 'ु', 'भ', 'ह', 'ो', '।']
English : ['Have', 'a', 'good', 'day', '.']
Lengths : 11 vs 5
--------------------------------------------------------------------------------

In [28]:
# Flatten all Hindi tokens
hindi_all_tokens = []

for hindi, english in parallel_data:
    hindi_all_tokens.extend(tokenize_text(hindi))


# Flatten all English tokens
english_all_tokens = []

for hindi, english in parallel_data:
    english_all_tokens.extend(tokenize_text(english))


# Vocabulary
hindi_vocab = set(hindi_all_tokens)
english_vocab = set(english_all_tokens)


print("Hindi Statistics")
print("----------------")
print("Total tokens:", len(hindi_all_tokens))
print("Vocabulary size:", len(hindi_vocab))
print("Average sentence length:", np.mean(
    parallel_df["Hindi Length"]
))


print("\nEnglish Statistics")
print("------------------")
print("Total tokens:", len(english_all_tokens))
print("Vocabulary size:", len(english_vocab))
print("Average sentence length:", np.mean(
    parallel_df["English Length"]
))

Hindi Statistics
----------------
Total tokens: 311
Vocabulary size: 68
Average sentence length: 15.55

English Statistics
------------------
Total tokens: 107
Vocabulary size: 58
Average sentence length: 5.35

In [29]:
parallel_stats = pd.DataFrame({
    "Language": ["Hindi", "English"],
    "Total Tokens": [
        len(hindi_all_tokens),
        len(english_all_tokens)
    ],
    "Vocabulary Size": [
        len(hindi_vocab),
        len(english_vocab)
    ],
    "Average Sentence Length": [
        np.mean(parallel_df["Hindi Length"]),
        np.mean(parallel_df["English Length"])
    ]
})

parallel_stats

  Language  Total Tokens  Vocabulary Size  Average Sentence Length
0    Hindi           311               68                    15.55
1  English           107               58                     5.35

In [30]:
code_mixed_sentences = [
    "Aaj mera college test hai.",
    "Mujhe Python programming bahut pasand hai.",
    "Kal assignment submit karna hai.",
    "Please mujhe ye file send kar do.",
    "Aaj lecture mein machine learning padha.",
    "Mera laptop bahut slow ho gaya hai.",
    "Tumne project complete kiya kya?",
    "Mujhe ek new notebook chahiye.",
    "Sir ne homework upload karne ko bola.",
    "Main abhi coding practice kar raha hoon.",
    "Aaj presentation ke liye prepare karna hai.",
    "Mujhe ye concept properly samajh nahi aaya."
]

print("Number of code-mixed sentences:", len(code_mixed_sentences))

for i, sentence in enumerate(code_mixed_sentences, 1):
    print(i, sentence)

Number of code-mixed sentences: 12
1 Aaj mera college test hai.
2 Mujhe Python programming bahut pasand hai.
3 Kal assignment submit karna hai.
4 Please mujhe ye file send kar do.
5 Aaj lecture mein machine learning padha.
6 Mera laptop bahut slow ho gaya hai.
7 Tumne project complete kiya kya?
8 Mujhe ek new notebook chahiye.
9 Sir ne homework upload karne ko bola.
10 Main abhi coding practice kar raha hoon.
11 Aaj presentation ke liye prepare karna hai.
12 Mujhe ye concept properly samajh nahi aaya.

In [31]:
english_words = {
    "college",
    "test",
    "python",
    "programming",
    "assignment",
    "submit",
    "please",
    "file",
    "send",
    "lecture",
    "machine",
    "learning",
    "laptop",
    "slow",
    "project",
    "complete",
    "new",
    "notebook",
    "homework",
    "upload",
    "presentation",
    "prepare",
    "coding",
    "practice",
    "concept",
    "properly"
}


def detect_language(token):
    """
    Simple rule-based language identification.
    This is only for demonstration and is not a full language
    identification model.
    """

    # Devanagari
    if re.search(r'[\u0900-\u097F]', token):
        return "Hindi"

    # English dictionary
    if token.lower() in english_words:
        return "English"

    # Romanized Hindi / unknown Roman word
    if re.fullmatch(r'[A-Za-z]+', token):
        return "Roman-Hindi/Other"

    return "Other"

In [32]:
code_mixed_analysis = []

for sentence in code_mixed_sentences:

    tokens = tokenize_text(sentence)

    for token in tokens:

        language = detect_language(token)

        code_mixed_analysis.append({
            "Sentence": sentence,
            "Token": token,
            "Language": language
        })


code_mixed_df = pd.DataFrame(code_mixed_analysis)

code_mixed_df

                                       Sentence     Token           Language
0                    Aaj mera college test hai.       Aaj  Roman-Hindi/Other
1                    Aaj mera college test hai.      mera  Roman-Hindi/Other
2                    Aaj mera college test hai.   college            English
3                    Aaj mera college test hai.      test            English
4                    Aaj mera college test hai.       hai  Roman-Hindi/Other
..                                          ...       ...                ...
81  Mujhe ye concept properly samajh nahi aaya.  properly            English
82  Mujhe ye concept properly samajh nahi aaya.    samajh  Roman-Hindi/Other
83  Mujhe ye concept properly samajh nahi aaya.      nahi  Roman-Hindi/Other
84  Mujhe ye concept properly samajh nahi aaya.      aaya  Roman-Hindi/Other
85  Mujhe ye concept properly samajh nahi aaya.         .              Other

[86 rows x 3 columns]

In [33]:
normalized_code_mixed = [
    normalize_indic_text(sentence)
    for sentence in code_mixed_sentences
]


code_mixed_output = pd.DataFrame({
    "Original Code-Mixed Text": code_mixed_sentences,
    "Normalized Text": normalized_code_mixed
})


code_mixed_output

,Original Code-Mixed Text,Normalized Text
0,Aaj mera college test hai.,aaj mera college test hai.
1,Mujhe Python programming bahut pasand hai.,mujhe python programming bahut pasand hai.
2,Kal assignment submit karna hai.,kal assignment submit karna hai.
3,Please mujhe ye file send kar do.,please mujhe ye file send kar do.
4,Aaj lecture mein machine learning padha.,aaj lecture mein machine learning padha.
5,Mera laptop bahut slow ho gaya hai.,mera laptop bahut slow ho gaya hai.
6,Tumne project complete kiya kya?,tumne project complete kiya kya?
7,Mujhe ek new notebook chahiye.,mujhe ek new notebook chahiye.
8,Sir ne homework upload karne ko bola.,sir ne homework upload karne ko bola.
9,Main abhi coding practice kar raha hoon.,main abhi coding practice kar raha hoon.
10,Aaj presentation ke liye prepare karna hai.,aaj presentation ke liye prepare karna hai.
11,Mujhe ye concept properly samajh nahi aaya.,mujhe ye concept properly samajh nahi aaya.

In [34]:
language_counts = code_mixed_df["Language"].value_counts()

print("Language/token categories:")
print(language_counts)

Language/token categories:
Language
Roman-Hindi/Other    48
English              26
Other                12
Name: count, dtype: int64

In [35]:
mixed_devanagari = [
    "आज मेरा college test है।",
    "मुझे Python programming पसंद है।",
    "कल assignment submit करना है।",
    "Please मुझे यह file send कर दो।",
    "आज lecture में machine learning पढ़ा।",
    "मेरा laptop बहुत slow है।",
    "तुमने project complete किया क्या?",
    "मुझे एक new notebook चाहिए।",
    "Sir ने homework upload करने को कहा।",
    "मैं coding practice कर रहा हूँ।"
]


for sentence in mixed_devanagari:
    normalized = normalize_indic_text(sentence)

    print("Original  :", sentence)
    print("Normalized:", normalized)
    print("-" * 70)

Original  : आज मेरा college test है।
Normalized: आज मेरा college test है।
----------------------------------------------------------------------
Original  : मुझे Python programming पसंद है।
Normalized: मुझे python programming पसंद है।
----------------------------------------------------------------------
Original  : कल assignment submit करना है।
Normalized: कल assignment submit करना है।
----------------------------------------------------------------------
Original  : Please मुझे यह file send कर दो।
Normalized: please मुझे यह file send कर दो।
----------------------------------------------------------------------
Original  : आज lecture में machine learning पढ़ा।
Normalized: आज lecture में machine learning पढ़ा।
----------------------------------------------------------------------
Original  : मेरा laptop बहुत slow है।
Normalized: मेरा laptop बहुत slow है।
----------------------------------------------------------------------
Original  : तुमने project complete किया क्या?
Normalized: तुमने project complete किया क्या?
----------------------------------------------------------------------
Original  : मुझे एक new notebook चाहिए।
Normalized: मुझे एक new notebook चाहिए।
----------------------------------------------------------------------
Original  : Sir ने homework upload करने को कहा।
Normalized: sir ने homework upload करने को कहा।
----------------------------------------------------------------------
Original  : मैं coding practice कर रहा हूँ।
Normalized: मैं coding practice कर रहा हूँ।
----------------------------------------------------------------------

In [36]:
def get_token_script(token):

    if re.search(r'[\u0900-\u097F]', token):
        return "Devanagari"

    elif re.fullmatch(r'[A-Za-z]+', token):
        return "Latin"

    else:
        return "Other"


mixed_script_rows = []

for sentence in mixed_devanagari:

    tokens = tokenize_text(sentence)

    for token in tokens:

        mixed_script_rows.append({
            "Sentence": sentence,
            "Token": token,
            "Script": get_token_script(token)
        })


mixed_script_df = pd.DataFrame(mixed_script_rows)

mixed_script_df

                            Sentence Token      Script
0           आज मेरा college test है।    आज  Devanagari
1           आज मेरा college test है।     म  Devanagari
2           आज मेरा college test है।     े  Devanagari
3           आज मेरा college test है।     र  Devanagari
4           आज मेरा college test है।     ा  Devanagari
..                               ...   ...         ...
112  मैं coding practice कर रहा हूँ।     ा  Devanagari
113  मैं coding practice कर रहा हूँ।     ह  Devanagari
114  मैं coding practice कर रहा हूँ।     ू  Devanagari
115  मैं coding practice कर रहा हूँ।     ँ  Devanagari
116  मैं coding practice कर रहा हूँ।     ।  Devanagari

[117 rows x 3 columns]

In [37]:
script_distribution = mixed_script_df["Script"].value_counts()

print("Script distribution in code-mixed data:")
print(script_distribution)

Script distribution in code-mixed data:
Script
Devanagari    93
Latin         23
Other          1
Name: count, dtype: int64

In [38]:
print("""
Challenges in parallel corpora:

1. Hindi and English have different sentence structures and word
   orders.

2. A Hindi sentence may require more or fewer words when translated
   into English.

3. Some words may not have a direct one-to-one translation.

4. Proper nouns and technical terms can occur in different forms.

5. Small manually created parallel datasets may not represent the
   full language.

6. Translation quality can vary depending on context.

Challenges in code-mixed text:

1. Two or more languages may occur in the same sentence.

2. Users may switch languages in the middle of a sentence.

3. Hindi can be written in Devanagari or Roman script.

4. Romanized Hindi does not have a single standard spelling.

5. English technical words such as Python, project and machine
   learning are commonly mixed with Indian languages.

6. Standard tokenizers and language identification tools may have
   difficulty identifying individual tokens correctly.

7. Social media text often contains abbreviations, emojis, repeated
   characters and spelling variations.

8. Context is important for deciding which language a Roman-script
   word belongs to.
""")

Challenges in parallel corpora:

1. Hindi and English have different sentence structures and word
   orders.

2. A Hindi sentence may require more or fewer words when translated
   into English.

3. Some words may not have a direct one-to-one translation.

4. Proper nouns and technical terms can occur in different forms.

5. Small manually created parallel datasets may not represent the
   full language.

6. Translation quality can vary depending on context.

Challenges in code-mixed text:

1. Two or more languages may occur in the same sentence.

2. Users may switch languages in the middle of a sentence.

3. Hindi can be written in Devanagari or Roman script.

4. Romanized Hindi does not have a single standard spelling.

5. English technical words such as Python, project and machine
   learning are commonly mixed with Indian languages.

6. Standard tokenizers and language identification tools may have
   difficulty identifying individual tokens correctly.

7. Social media text often contains abbreviations, emojis, repeated
   characters and spelling variations.

8. Context is important for deciding which language a Roman-script
   word belongs to.